"use client";

import { FormEvent, useState } from "react";
import { getSupabaseClient } from "@/lib/supabase/client";
import AppHeader from "@/app/components/app-header";
import styles from "./game-creator.module.css";

type GameMode = "single_player" | "multiplayer";
const examples = ["A game where we roast each other with AI", "Truth or dare but make it weirder", "A detective game with a time limit"];

function draftDefinition(mode: GameMode) { return { schemaVersion: 1, metadata: { status: "draft", launchMode: mode }, config: { mode }, state: {}, players: {}, entities: [], scenes: [], actions: [], rules: [], phases: [], winConditions: [], visuals: {} }; }

export default function GameCreator({ mode, title, roomId }: { mode: GameMode; title: string; roomId?: string }) {
  const [idea, setIdea] = useState("");
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");
  const [isSubmitting, setIsSubmitting] = useState(false);

  async function createGame(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const prompt = idea.trim();
    if (!prompt) { setError("Tell Plizzy a little about your game first."); return; }
    const supabase = getSupabaseClient();
    if (!supabase) { setError("Supabase is not connected yet. Add the public project URL and key to .env.local."); return; }
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) { setError("Please sign in before creating a game."); return; }
    setError(""); setSuccess(""); setIsSubmitting(true);
    const { data: game, error: gameError } = await supabase.from("games").insert({ creator_id: user.id, title, summary: prompt.slice(0, 500), visibility: "private" }).select("id").single();
    if (gameError || !game) { setError(gameError?.message ?? "We couldn’t create that game."); setIsSubmitting(false); return; }
    const { data: version, error: versionError } = await supabase.from("game_versions").insert({ game_id: game.id, version_number: 1, prompt, rules_markdown: "# Draft\n\nGame rules will be generated by the trusted creation workflow.", min_players: mode === "single_player" ? 1 : 2, max_players: mode === "single_player" ? 1 : 8, game_mode: mode, definition: draftDefinition(mode), generation_metadata: { workflow: "manual-draft", agentSdk: false } }).select("id").single();
    if (versionError || !version) { setError(versionError?.message ?? "The game was created, but its first version could not be saved."); setIsSubmitting(false); return; }
    const { error: latestError } = await supabase.from("games").update({ latest_version_id: version.id }).eq("id", game.id);
    if (latestError) { setError(latestError.message); setIsSubmitting(false); return; }
    if (mode === "multiplayer") {
      if (roomId) {
        const { error: roomGameError } = await supabase.from("room_games").insert({ room_id: roomId, game_version_id: version.id, added_by: user.id, position: 0 });
        if (roomGameError) { setError(roomGameError.message); setIsSubmitting(false); return; }
        setSuccess("Draft saved and added to this room.");
      } else {
        const { data: roomRows, error: roomError } = await supabase.rpc("create_room_for_game", { target_game_version_id: version.id });
        const room = roomRows?.[0];
        if (roomError || !room) { setError(roomError?.message ?? "Your game is ready, but its room could not be created."); setIsSubmitting(false); return; }
        setSuccess(`Draft saved in ${room.room_name}. Invite code: ${room.invite_code}.`);
      }
    } else setSuccess("Draft saved. The game-generation workflow is ready for its next step.");
    setIsSubmitting(false);
  }

  return <main className={styles.stage}><section className={styles.phone}>
    <AppHeader backHref="/footer/create" />
    <div className={styles.content}><p className={styles.mode}>{roomId ? "ADDING TO YOUR ROOM" : mode === "multiplayer" ? "MULTIPLAYER GAME" : "SINGLE PLAYER GAME"}</p><h1>Create a game <span>✨</span></h1><p className={styles.subtitle}>Describe your game idea and let Plizzy bring it to life.</p><p className={styles.title}>“{title}”</p>
      <form onSubmit={createGame}><textarea value={idea} onChange={(event) => setIdea(event.target.value)} maxLength={500} placeholder="E.g. a drawing game where one person draws and others guess, but with a twist..." aria-label="Describe your game idea" /><p className={styles.counter}>{idea.length}/500</p><button type="button" className={styles.surprise} onClick={() => setIdea("Surprise me with a playful social game that is easy to learn and fun to replay.")}>🪄 &nbsp; Surprise me 🎲</button>{error && <p className={styles.error} role="alert">{error}</p>}{success && <p className={styles.success} role="status">{success}</p>}<button className={styles.submit} type="submit" disabled={isSubmitting}>{isSubmitting ? "Saving your game…" : "Create Game"}</button></form>
      <h2>Examples</h2><div className={styles.examples}>{examples.map((example) => <button type="button" key={example} onClick={() => setIdea(example)}>{example}</button>)}</div>
    </div>
  </section></main>;
}
