"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { getSupabaseClient } from "@/lib/supabase/client";
import styles from "../rooms.module.css";

type Room = { id: string; name: string; invite_code: string; host_id: string };
type Member = { user_id: string; role: "host" | "member"; profiles: { display_name: string; username: string } | null };
type RoomGame = { game_version_id: string; game_versions: { game_mode: "single_player" | "multiplayer"; game: { title: string; summary: string | null } | null } | null };

export default function RoomDetail({ roomId }: { roomId: string }) {
  const [room, setRoom] = useState<Room | null>(null); const [members, setMembers] = useState<Member[]>([]); const [games, setGames] = useState<RoomGame[]>([]); const [currentUserId, setCurrentUserId] = useState(""); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { async function load() { const supabase = getSupabaseClient(); if (!supabase) { setError("Supabase is not connected yet."); return; } const { data: { user } } = await supabase.auth.getUser(); if (!user) { setError("Sign in to view this room."); return; } setCurrentUserId(user.id); const [{ data: roomRow, error: roomError }, { data: memberRows, error: membersError }, { data: gameRows, error: gamesError }] = await Promise.all([supabase.from("rooms").select("id, name, invite_code, host_id").eq("id", roomId).single(), supabase.from("room_members").select("user_id, role, profiles(display_name, username)").eq("room_id", roomId), supabase.from("room_games").select("game_version_id, game_versions!room_games_game_version_id_fkey(game_mode, game:games!game_versions_game_id_fkey(title, summary))").eq("room_id", roomId).order("position")]); if (roomError || membersError || gamesError) { setError(roomError?.message ?? membersError?.message ?? gamesError?.message ?? "Room unavailable."); return; } const normalizedMembers = (memberRows as unknown as Array<Member & { profiles: Member["profiles"] | Member["profiles"][] }>).map((member) => ({ ...member, profiles: Array.isArray(member.profiles) ? member.profiles[0] ?? null : member.profiles })); setRoom(roomRow as Room); setMembers(normalizedMembers); setGames(gameRows as unknown as RoomGame[]); } void load(); }, [roomId]);
  const isAdmin = room?.host_id === currentUserId;
  async function copyInvite() { if (!room) return; await navigator.clipboard.writeText(room.invite_code); setNotice("Invite code copied — send it to your friends."); }
  async function removeMember(userId: string) { const supabase = getSupabaseClient(); if (!supabase) return; const { error: removeError } = await supabase.rpc("remove_room_member", { target_room_id: roomId, target_user_id: userId }); if (removeError) { setError(removeError.message); return; } setMembers((current) => current.filter((member) => member.user_id !== userId)); }
  return <main className={styles.detailStage}><section className={styles.detailPhone}><header className={styles.detailHeader}><Link href="/footer/rooms">‹</Link><p>plizzy</p></header>{room && <div className={styles.detailContent}><div className={styles.hero}><p>YOUR GAME NIGHT</p><h1>{room.name}</h1><span>♟</span></div><button className={styles.invite} onClick={() => void copyInvite()}><b>Invite friends</b><small>Share code <strong>{room.invite_code}</strong></small><i>↗</i></button>{notice && <p className={styles.notice}>{notice}</p>}<div className={styles.sectionTitle}><div><p>GAME SHELF</p><h2>{games.length} {games.length === 1 ? "game" : "games"}</h2></div>{isAdmin && <Link href={`/footer/create?room=${roomId}`}>+ Add game</Link>}</div><div className={styles.gameShelf}>{games.map((entry, index) => <article className={`${styles.gameCard} ${index % 2 ? styles.yellow : ""}`} key={entry.game_version_id}><span>{entry.game_versions?.game_mode === "multiplayer" ? "🎲" : "✨"}</span><p>{entry.game_versions?.game_mode === "multiplayer" ? "MULTIPLAYER" : "SOLO"}</p><h3>{entry.game_versions?.game?.title ?? "Untitled game"}</h3><small>{entry.game_versions?.game?.summary ?? "Ready for the next round."}</small></article>)}</div><div className={styles.sectionTitle}><div><p>THE GROUP</p><h2>{members.length} {members.length === 1 ? "member" : "members"}</h2></div>{isAdmin && <span className={styles.admin}>Admin</span>}</div><div className={styles.members}>{members.map((member) => <div className={styles.member} key={member.user_id}><span>{(member.profiles?.display_name ?? "P").charAt(0).toUpperCase()}</span><div><strong>{member.profiles?.display_name ?? member.profiles?.username ?? "Player"}</strong><small>{member.role === "host" ? "Room admin" : "Member"}</small></div>{isAdmin && member.role !== "host" && <button onClick={() => void removeMember(member.user_id)}>Remove</button>}</div>)}</div></div>}{error && <p className={styles.detailError}>{error}</p>}</section></main>;
}
