"use client";

import Link from "next/link";
import { ChangeEvent, FormEvent, useEffect, useRef, useState } from "react";
import { getSupabaseClient } from "@/lib/supabase/client";
import styles from "./profile.module.css";

type Account = { id: string; email: string; username: string; displayName: string; avatarUrl: string | null };

export default function ProfileSettings() {
  const [account, setAccount] = useState<Account | null>(null);
  const [username, setUsername] = useState("");
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);
  const fileInput = useRef<HTMLInputElement>(null);
  useEffect(() => { async function load() { const supabase = getSupabaseClient(); if (!supabase) { setError("Supabase is not connected yet."); return; } const { data: { user } } = await supabase.auth.getUser(); if (!user || !user.email) { window.location.assign("/"); return; } const { data, error: profileError } = await supabase.from("profiles").select("username, display_name, avatar_url").eq("id", user.id).single(); if (profileError || !data) { setError(profileError?.message ?? "We couldn't find your profile."); return; } setAccount({ id: user.id, email: user.email, username: data.username, displayName: data.display_name, avatarUrl: data.avatar_url }); setUsername(data.username); } void load(); }, []);
  async function saveUsername(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!account) return; const value = username.trim().toLowerCase(); if (!/^[a-zA-Z0-9_]{3,30}$/.test(value)) { setError("Use 3–30 letters, numbers, or underscores."); return; } const supabase = getSupabaseClient(); if (!supabase) return; setSaving(true); setError(""); const { error: updateError } = await supabase.from("profiles").update({ username: value }).eq("id", account.id); setSaving(false); if (updateError) { setError(updateError.code === "23505" ? "That username is already taken." : updateError.message); return; } setAccount({ ...account, username: value }); setNotice("Username updated."); }
  async function uploadAvatar(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; if (!file || !account) return; if (!['image/jpeg', 'image/png', 'image/webp'].includes(file.type) || file.size > 2 * 1024 * 1024) { setError("Use a JPG, PNG, or WebP image under 2 MB."); return; } const extension = file.name.split(".").pop()?.toLowerCase() || "png"; const path = `${account.id}/avatar.${extension}`; const supabase = getSupabaseClient(); if (!supabase) return; setSaving(true); setError(""); const { error: uploadError } = await supabase.storage.from("avatars").upload(path, file, { upsert: true, contentType: file.type }); if (uploadError) { setError(uploadError.message); setSaving(false); return; } const { data: publicUrl } = supabase.storage.from("avatars").getPublicUrl(path); const avatarUrl = `${publicUrl.publicUrl}?v=${Date.now()}`; const { error: updateError } = await supabase.from("profiles").update({ avatar_url: avatarUrl }).eq("id", account.id); setSaving(false); if (updateError) { setError(updateError.message); return; } setAccount({ ...account, avatarUrl }); setNotice("Avatar updated."); }
  async function signOut() { const supabase = getSupabaseClient(); if (supabase) await supabase.auth.signOut(); window.location.assign("/"); }
  const initial = (account?.displayName || account?.username || "P").charAt(0).toUpperCase();
  return <main className={styles.stage}><section className={styles.phone}><header><Link href="/footer/home" aria-label="Back to home">‹</Link><p>plizzy</p></header><div className={styles.content}><p className={styles.eyebrow}>YOUR CORNER OF PLIZZY</p><h1>Profile & settings</h1>{!account && !error && <p className={styles.loading}>Loading your profile…</p>}{account && <><section className={styles.profileCard}><button type="button" className={styles.avatar} onClick={() => fileInput.current?.click()} style={account.avatarUrl ? { backgroundImage: `url(${account.avatarUrl})` } : undefined}>{account.avatarUrl ? null : initial}<span>Change</span></button><input ref={fileInput} className={styles.fileInput} type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => void uploadAvatar(event)} /><div><strong>{account.displayName}</strong><small>@{account.username}</small><button type="button" onClick={() => fileInput.current?.click()}>{saving ? "Working…" : "Upload photo"}</button></div></section><section className={styles.section}><div className={styles.sectionHeading}><span>✦</span><div><h2>Your username</h2><p>This is how friends find you.</p></div></div><form onSubmit={saveUsername}><label>Username<input value={username} onChange={(event) => setUsername(event.target.value)} autoCapitalize="none" minLength={3} maxLength={30} required /></label><button type="submit" disabled={saving}>Save username</button></form></section><section className={styles.section}><div className={styles.sectionHeading}><span>✉</span><div><h2>Email</h2><p>Your sign-in email is managed by your account.</p></div></div><p className={styles.readonly}>{account.email}</p></section><section className={styles.section}><div className={styles.sectionHeading}><span>⌁</span><div><h2>Account</h2><p>Safely leave this device whenever you need.</p></div></div><button className={styles.logout} type="button" onClick={() => void signOut()}>Log out</button></section></>}{error && <p className={styles.error} role="alert">{error}</p>}{notice && <p className={styles.notice} role="status">{notice}</p>}</div></section></main>;
}
